### ISSUE TITLE
プロジェクト一覧の作成

### ISSUE THREAD

**Issue by pyCapybara** [righ/walkframe#3]
# 目的

- プロジェクトレコードを一覧表示する為

# 入出力

## 入力

<table>
    <tr>
        <td>url</td>
        <td colspan="2">/project/</td>
    </tr>
    <tr>
        <td>parameter</td>
        <td>name</td>
        <td>与えられた文字列でプロジェクト名を部分一致フィルタリングする(大文字小文字区別なし)</td>
    </tr>
    <tr>
        <td>parameter</td>
        <td>description</td>
        <td>与えられた文字列でプロジェクト概要を部分一致フィルタリングする(大文字小文字区別なし)</td>
    </tr>
</table>

## 出力

<table>
    <tr>
        <td>id</td>
        <td>プロジェクトID</td>
    </tr>
    <tr>
        <td>name</td>
        <td>プロジェクト名(プロジェクト詳細ページへのリンクを貼る)</td>
    </tr>
    <tr>
        <td>description</td>
        <td>プロジェクトの説明</td>
    </tr>
</table>

**Comment by righ** [comment]
URLの形式を `/projects/` から `/project/` に更新しました。

**Comment by righ** [comment]
マージしたので閉じ
